### ISSUE TITLE
Better README description

### ISSUE THREAD

**Issue by felipebonezi** [justapagamentos/jst-ng-validators#4]
We need to improve our README description using all validations samples.

**Comment by raisiqueira** [comment]
@felipebonezi We have an example running on [Stackblitz](https://stackblitz.com/edit/ng-validators-jst), and a example here (in the [_projects_ folder](https://github.com/justapagamentos/jst-ng-validators/tree/master/projects/justa/br-validators#examples)).

**Comment by raisiqueira** [comment]
Done! https://github.com/justapagamentos/jst-ng-validators/pull/6
